[package]
name = "chat_async"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tokio = { version = "1.46.1", features = ["full"] }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
incremental = false
